export const initialProjects = [
  {
    name: 'First project',
    nodes: [
      {
        id: 'dndnode_dndnode_1',
        position: { x: 203, y: 104.5 },
        selectable: false,
        data: {
          inputs: { input1: false, input2: false },
          outputs: { output1: false },
          logic: 'or',
          connected: {
            after: [
              {
                targetNode: {
                  width: 80,
                  height: 50,
                  id: 'dndnode_dndnode_5',
                  position: { x: 332, y: 230.5 },
                  selectable: false,
                  data: {
                    inputs: { input1: false, input2: true },
                    outputs: { output1: false },
                    logic: 'nor',
                    connected: { after: [], before: [] },
                  },
                  type: 'custom',
                  positionAbsolute: { x: 332, y: 230.5 },
                  dragging: false,
                },
                edgeAfter: {
                  source: 'dndnode_dndnode_1',
                  sourceHandle: 'output1',
                  target: 'dndnode_dndnode_5',
                  targetHandle: 'input1',
                  id: 'reactflow__edge-dndnode_dndnode_1output1-dndnode_dndnode_5input1',
                  type: 'custom',
                },
              },
              {
                targetNode: {
                  width: 80,
                  height: 50,
                  id: 'dndnode_dndnode_9',
                  position: { x: 339, y: 133.5 },
                  selectable: false,
                  data: {
                    inputs: { input1: false, input2: false },
                    outputs: { output1: false },
                    logic: 'and',
                    connected: { after: [], before: [] },
                  },
                  type: 'custom',
                  positionAbsolute: { x: 339, y: 133.5 },
                  dragging: false,
                },
                edgeAfter: {
                  source: 'dndnode_dndnode_1',
                  sourceHandle: 'output1',
                  target: 'dndnode_dndnode_9',
                  targetHandle: 'input1',
                  id: 'reactflow__edge-dndnode_dndnode_1output1-dndnode_dndnode_9input1',
                  type: 'custom',
                },
              },
            ],
            before: [],
          },
        },
        type: 'in',
        width: 44,
        height: 44,
        dragging: false,
        positionAbsolute: { x: 203, y: 104.5 },
      },
      {
        id: 'dndnode_dndnode_2',
        position: { x: 203, y: 186.5 },
        selectable: false,
        data: {
          inputs: { input1: false, input2: false },
          outputs: { output1: false },
          logic: 'or',
          connected: {
            after: [
              {
                targetNode: {
                  width: 80,
                  height: 50,
                  id: 'dndnode_dndnode_5',
                  position: { x: 332, y: 230.5 },
                  selectable: false,
                  data: {
                    inputs: { input1: false, input2: true },
                    outputs: { output1: false },
                    logic: 'nor',
                    connected: { after: [], before: [] },
                  },
                  type: 'custom',
                  positionAbsolute: { x: 332, y: 230.5 },
                  dragging: false,
                },
                edgeAfter: {
                  source: 'dndnode_dndnode_2',
                  sourceHandle: 'output1',
                  target: 'dndnode_dndnode_5',
                  targetHandle: 'input2',
                  id: 'reactflow__edge-dndnode_dndnode_2output1-dndnode_dndnode_5input2',
                  type: 'custom',
                },
              },
              {
                targetNode: {
                  width: 80,
                  height: 50,
                  id: 'dndnode_dndnode_9',
                  position: { x: 339, y: 133.5 },
                  selectable: false,
                  data: {
                    inputs: { input1: false, input2: true },
                    outputs: { output1: false },
                    logic: 'and',
                    connected: { after: [], before: [] },
                  },
                  type: 'custom',
                  positionAbsolute: { x: 339, y: 133.5 },
                  dragging: false,
                },
                edgeAfter: {
                  source: 'dndnode_dndnode_2',
                  sourceHandle: 'output1',
                  target: 'dndnode_dndnode_9',
                  targetHandle: 'input2',
                  id: 'reactflow__edge-dndnode_dndnode_2output1-dndnode_dndnode_9input2',
                  type: 'custom',
                },
              },
            ],
            before: [],
          },
        },
        type: 'in',
        width: 44,
        height: 44,
        positionAbsolute: { x: 203, y: 186.5 },
        dragging: false,
      },
      {
        id: 'dndnode_dndnode_3',
        position: { x: 202, y: 270.5 },
        selectable: false,
        data: {
          inputs: { input1: false, input2: false },
          outputs: { output1: false },
          logic: 'or',
          connected: {
            after: [
              {
                targetNode: {
                  width: 80,
                  height: 50,
                  id: 'dndnode_dndnode_7',
                  position: { x: 592, y: 202.5 },
                  selectable: false,
                  data: {
                    inputs: { input1: true, input2: false },
                    outputs: { output1: false },
                    logic: 'and',
                    connected: { after: [], before: [] },
                  },
                  type: 'custom',
                  positionAbsolute: { x: 592, y: 202.5 },
                  dragging: false,
                },
                edgeAfter: {
                  source: 'dndnode_dndnode_3',
                  sourceHandle: 'output1',
                  target: 'dndnode_dndnode_7',
                  targetHandle: 'input2',
                  id: 'reactflow__edge-dndnode_dndnode_3output1-dndnode_dndnode_7input2',
                  type: 'custom',
                },
              },
            ],
            before: [],
          },
        },
        type: 'in',
        width: 44,
        height: 44,
        positionAbsolute: { x: 202, y: 270.5 },
        dragging: false,
      },
      {
        id: 'dndnode_dndnode_5',
        position: { x: 332, y: 230.5 },
        selectable: false,
        data: {
          inputs: { input1: false, input2: false },
          outputs: { output1: true },
          logic: 'nor',
          connected: {
            after: [
              {
                targetNode: {
                  width: 80,
                  height: 50,
                  id: 'dndnode_dndnode_10',
                  position: { x: 460, y: 170.5 },
                  selectable: false,
                  data: {
                    inputs: { input1: false, input2: true },
                    outputs: { output1: true },
                    logic: 'xor',
                    connected: { after: [], before: [] },
                  },
                  type: 'custom',
                  positionAbsolute: { x: 460, y: 170.5 },
                  dragging: false,
                },
                edgeAfter: {
                  source: 'dndnode_dndnode_5',
                  sourceHandle: 'output1',
                  target: 'dndnode_dndnode_10',
                  targetHandle: 'input2',
                  id: 'reactflow__edge-dndnode_dndnode_5output1-dndnode_dndnode_10input2',
                  type: 'custom',
                },
              },
            ],
            before: [
              {
                sourceNode: {
                  width: 44,
                  height: 44,
                  id: 'dndnode_dndnode_1',
                  position: { x: 205, y: 104.5 },
                  selectable: false,
                  data: {
                    inputs: { input1: false, input2: false },
                    outputs: { output1: false },
                    logic: 'or',
                    connected: { after: [], before: [] },
                  },
                  type: 'in',
                  dragging: false,
                  positionAbsolute: { x: 205, y: 104.5 },
                },
                edgeBefore: {
                  source: 'dndnode_dndnode_1',
                  sourceHandle: 'output1',
                  target: 'dndnode_dndnode_5',
                  targetHandle: 'input1',
                  id: 'reactflow__edge-dndnode_dndnode_1output1-dndnode_dndnode_5input1',
                  type: 'custom',
                },
              },
              {
                sourceNode: {
                  width: 44,
                  height: 44,
                  id: 'dndnode_dndnode_2',
                  position: { x: 203, y: 186.5 },
                  selectable: false,
                  data: {
                    inputs: { input1: false, input2: false },
                    outputs: { output1: false },
                    logic: 'or',
                    connected: { after: [], before: [] },
                  },
                  type: 'in',
                  positionAbsolute: { x: 203, y: 186.5 },
                  dragging: false,
                },
                edgeBefore: {
                  source: 'dndnode_dndnode_2',
                  sourceHandle: 'output1',
                  target: 'dndnode_dndnode_5',
                  targetHandle: 'input2',
                  id: 'reactflow__edge-dndnode_dndnode_2output1-dndnode_dndnode_5input2',
                  type: 'custom',
                },
              },
            ],
          },
        },
        type: 'custom',
        width: 80,
        height: 50,
        positionAbsolute: { x: 332, y: 230.5 },
        dragging: false,
      },
      {
        id: 'dndnode_dndnode_7',
        position: { x: 569, y: 240.5 },
        selectable: false,
        data: {
          inputs: { input1: true, input2: false },
          outputs: { output1: false },
          logic: 'and',
          connected: {
            after: [
              {
                targetNode: {
                  width: 44,
                  height: 44,
                  id: 'dndnode_dndnode_8',
                  position: { x: 701, y: 258.5 },
                  selectable: false,
                  data: {
                    inputs: { input1: false },
                    outputs: {},
                    logic: 'or',
                    connected: { after: [], before: [] },
                  },
                  type: 'out',
                  positionAbsolute: { x: 701, y: 258.5 },
                  dragging: false,
                },
                edgeAfter: {
                  source: 'dndnode_dndnode_7',
                  sourceHandle: 'output1',
                  target: 'dndnode_dndnode_8',
                  targetHandle: 'input1',
                  id: 'reactflow__edge-dndnode_dndnode_7output1-dndnode_dndnode_8input1',
                  type: 'custom',
                },
              },
            ],
            before: [
              {
                sourceNode: {
                  width: 44,
                  height: 44,
                  id: 'dndnode_dndnode_3',
                  position: { x: 207, y: 271.5 },
                  selectable: false,
                  data: {
                    inputs: { input1: true, input2: false },
                    outputs: { output1: true },
                    logic: 'or',
                    connected: { after: [], before: [] },
                  },
                  type: 'in',
                  positionAbsolute: { x: 207, y: 271.5 },
                  dragging: false,
                },
                edgeBefore: {
                  source: 'dndnode_dndnode_3',
                  sourceHandle: 'output1',
                  target: 'dndnode_dndnode_7',
                  targetHandle: 'input2',
                  id: 'reactflow__edge-dndnode_dndnode_3output1-dndnode_dndnode_7input2',
                  type: 'custom',
                },
              },
              {
                sourceNode: {
                  width: 80,
                  height: 50,
                  id: 'dndnode_dndnode_10',
                  position: { x: 460, y: 170.5 },
                  selectable: false,
                  data: {
                    inputs: { input1: false, input2: true },
                    outputs: { output1: true },
                    logic: 'xor',
                    connected: { after: [], before: [] },
                  },
                  type: 'custom',
                  positionAbsolute: { x: 460, y: 170.5 },
                  dragging: false,
                },
                edgeBefore: {
                  source: 'dndnode_dndnode_10',
                  sourceHandle: 'output1',
                  target: 'dndnode_dndnode_7',
                  targetHandle: 'input1',
                  id: 'reactflow__edge-dndnode_dndnode_10output1-dndnode_dndnode_7input1',
                  type: 'custom',
                },
              },
            ],
          },
        },
        type: 'custom',
        width: 80,
        height: 50,
        positionAbsolute: { x: 569, y: 240.5 },
        dragging: false,
      },
      {
        id: 'dndnode_dndnode_8',
        position: { x: 701, y: 258.5 },
        selectable: false,
        data: {
          inputs: { input1: false },
          outputs: {},
          logic: 'or',
          connected: {
            after: [],
            before: [
              {
                sourceNode: {
                  width: 80,
                  height: 50,
                  id: 'dndnode_dndnode_7',
                  position: { x: 569, y: 253.5 },
                  selectable: false,
                  data: {
                    inputs: { input1: true, input2: false },
                    outputs: { output1: false },
                    logic: 'and',
                    connected: { after: [], before: [] },
                  },
                  type: 'custom',
                  positionAbsolute: { x: 569, y: 253.5 },
                  dragging: false,
                },
                edgeBefore: {
                  source: 'dndnode_dndnode_7',
                  sourceHandle: 'output1',
                  target: 'dndnode_dndnode_8',
                  targetHandle: 'input1',
                  id: 'reactflow__edge-dndnode_dndnode_7output1-dndnode_dndnode_8input1',
                  type: 'custom',
                },
              },
            ],
          },
        },
        type: 'out',
        width: 44,
        height: 44,
        positionAbsolute: { x: 701, y: 258.5 },
        dragging: false,
      },
      {
        id: 'dndnode_dndnode_9',
        position: { x: 339, y: 133.5 },
        selectable: false,
        data: {
          inputs: { input1: false, input2: false },
          outputs: { output1: false },
          logic: 'and',
          connected: {
            after: [
              {
                targetNode: {
                  width: 80,
                  height: 50,
                  id: 'dndnode_dndnode_10',
                  position: { x: 460, y: 170.5 },
                  selectable: false,
                  data: {
                    inputs: { input1: false, input2: false },
                    outputs: { output1: false },
                    logic: 'xor',
                    connected: { after: [], before: [] },
                  },
                  type: 'custom',
                  positionAbsolute: { x: 460, y: 170.5 },
                  dragging: false,
                },
                edgeAfter: {
                  source: 'dndnode_dndnode_9',
                  sourceHandle: 'output1',
                  target: 'dndnode_dndnode_10',
                  targetHandle: 'input1',
                  id: 'reactflow__edge-dndnode_dndnode_9output1-dndnode_dndnode_10input1',
                  type: 'custom',
                },
              },
            ],
            before: [
              {
                sourceNode: {
                  width: 44,
                  height: 44,
                  id: 'dndnode_dndnode_1',
                  position: { x: 205, y: 104.5 },
                  selectable: false,
                  data: {
                    inputs: { input1: false, input2: false },
                    outputs: { output1: false },
                    logic: 'or',
                    connected: { after: [], before: [] },
                  },
                  type: 'in',
                  dragging: false,
                  positionAbsolute: { x: 205, y: 104.5 },
                },
                edgeBefore: {
                  source: 'dndnode_dndnode_1',
                  sourceHandle: 'output1',
                  target: 'dndnode_dndnode_9',
                  targetHandle: 'input1',
                  id: 'reactflow__edge-dndnode_dndnode_1output1-dndnode_dndnode_9input1',
                  type: 'custom',
                },
              },
              {
                sourceNode: {
                  width: 44,
                  height: 44,
                  id: 'dndnode_dndnode_2',
                  position: { x: 203, y: 186.5 },
                  selectable: false,
                  data: {
                    inputs: { input1: false, input2: false },
                    outputs: { output1: false },
                    logic: 'or',
                    connected: { after: [], before: [] },
                  },
                  type: 'in',
                  positionAbsolute: { x: 203, y: 186.5 },
                  dragging: false,
                },
                edgeBefore: {
                  source: 'dndnode_dndnode_2',
                  sourceHandle: 'output1',
                  target: 'dndnode_dndnode_9',
                  targetHandle: 'input2',
                  id: 'reactflow__edge-dndnode_dndnode_2output1-dndnode_dndnode_9input2',
                  type: 'custom',
                },
              },
            ],
          },
        },
        type: 'custom',
        width: 80,
        height: 50,
        positionAbsolute: { x: 339, y: 133.5 },
        dragging: false,
      },
      {
        id: 'dndnode_dndnode_10',
        position: { x: 460, y: 170.5 },
        selectable: false,
        data: {
          inputs: { input1: false, input2: true },
          outputs: { output1: true },
          logic: 'xor',
          connected: {
            after: [
              {
                targetNode: {
                  width: 80,
                  height: 50,
                  id: 'dndnode_dndnode_7',
                  position: { x: 569, y: 253.5 },
                  selectable: false,
                  data: {
                    inputs: { input1: true, input2: true },
                    outputs: { output1: true },
                    logic: 'and',
                    connected: { after: [], before: [] },
                  },
                  type: 'custom',
                  positionAbsolute: { x: 569, y: 253.5 },
                  dragging: false,
                },
                edgeAfter: {
                  source: 'dndnode_dndnode_10',
                  sourceHandle: 'output1',
                  target: 'dndnode_dndnode_7',
                  targetHandle: 'input1',
                  id: 'reactflow__edge-dndnode_dndnode_10output1-dndnode_dndnode_7input1',
                  type: 'custom',
                },
              },
            ],
            before: [
              {
                sourceNode: {
                  width: 80,
                  height: 50,
                  id: 'dndnode_dndnode_9',
                  position: { x: 339, y: 133.5 },
                  selectable: false,
                  data: {
                    inputs: { input1: false, input2: false },
                    outputs: { output1: false },
                    logic: 'and',
                    connected: { after: [], before: [] },
                  },
                  type: 'custom',
                  positionAbsolute: { x: 339, y: 133.5 },
                  dragging: false,
                },
                edgeBefore: {
                  source: 'dndnode_dndnode_9',
                  sourceHandle: 'output1',
                  target: 'dndnode_dndnode_10',
                  targetHandle: 'input1',
                  id: 'reactflow__edge-dndnode_dndnode_9output1-dndnode_dndnode_10input1',
                  type: 'custom',
                },
              },
              {
                sourceNode: {
                  width: 80,
                  height: 50,
                  id: 'dndnode_dndnode_5',
                  position: { x: 332, y: 230.5 },
                  selectable: false,
                  data: {
                    inputs: { input1: false, input2: false },
                    outputs: { output1: true },
                    logic: 'nor',
                    connected: { after: [], before: [] },
                  },
                  type: 'custom',
                  positionAbsolute: { x: 332, y: 230.5 },
                  dragging: false,
                },
                edgeBefore: {
                  source: 'dndnode_dndnode_5',
                  sourceHandle: 'output1',
                  target: 'dndnode_dndnode_10',
                  targetHandle: 'input2',
                  id: 'reactflow__edge-dndnode_dndnode_5output1-dndnode_dndnode_10input2',
                  type: 'custom',
                },
              },
            ],
          },
        },
        type: 'custom',
        width: 80,
        height: 50,
        positionAbsolute: { x: 460, y: 170.5 },
        dragging: false,
      },
    ],
    edges: [
      {
        source: 'dndnode_dndnode_1',
        sourceHandle: 'output1',
        target: 'dndnode_dndnode_5',
        targetHandle: 'input1',
        id: 'reactflow__edge-dndnode_dndnode_1output1-dndnode_dndnode_5input1',
        type: 'custom',
      },
      {
        source: 'dndnode_dndnode_2',
        sourceHandle: 'output1',
        target: 'dndnode_dndnode_5',
        targetHandle: 'input2',
        id: 'reactflow__edge-dndnode_dndnode_2output1-dndnode_dndnode_5input2',
        type: 'custom',
      },
      {
        source: 'dndnode_dndnode_3',
        sourceHandle: 'output1',
        target: 'dndnode_dndnode_7',
        targetHandle: 'input2',
        id: 'reactflow__edge-dndnode_dndnode_3output1-dndnode_dndnode_7input2',
        type: 'custom',
      },
      {
        source: 'dndnode_dndnode_7',
        sourceHandle: 'output1',
        target: 'dndnode_dndnode_8',
        targetHandle: 'input1',
        id: 'reactflow__edge-dndnode_dndnode_7output1-dndnode_dndnode_8input1',
        type: 'custom',
      },
      {
        source: 'dndnode_dndnode_1',
        sourceHandle: 'output1',
        target: 'dndnode_dndnode_9',
        targetHandle: 'input1',
        id: 'reactflow__edge-dndnode_dndnode_1output1-dndnode_dndnode_9input1',
        type: 'custom',
      },
      {
        source: 'dndnode_dndnode_2',
        sourceHandle: 'output1',
        target: 'dndnode_dndnode_9',
        targetHandle: 'input2',
        id: 'reactflow__edge-dndnode_dndnode_2output1-dndnode_dndnode_9input2',
        type: 'custom',
      },
      {
        source: 'dndnode_dndnode_9',
        sourceHandle: 'output1',
        target: 'dndnode_dndnode_10',
        targetHandle: 'input1',
        id: 'reactflow__edge-dndnode_dndnode_9output1-dndnode_dndnode_10input1',
        type: 'custom',
      },
      {
        source: 'dndnode_dndnode_5',
        sourceHandle: 'output1',
        target: 'dndnode_dndnode_10',
        targetHandle: 'input2',
        id: 'reactflow__edge-dndnode_dndnode_5output1-dndnode_dndnode_10input2',
        type: 'custom',
      },
      {
        source: 'dndnode_dndnode_10',
        sourceHandle: 'output1',
        target: 'dndnode_dndnode_7',
        targetHandle: 'input1',
        id: 'reactflow__edge-dndnode_dndnode_10output1-dndnode_dndnode_7input1',
        type: 'custom',
      },
    ],
    autosave: false,
    upToDate: true,
  },
  {
    name: 'Block exapmle - 1bit adder',
    nodes: [
      {
        id: 'dndnode_dndnode_1',
        position: { x: 142, y: 112.5 },
        selectable: false,
        data: {
          inputs: { input1: false, input2: false },
          outputs: { output1: false },
          logic: 'blockInput',
          connected: {
            after: [
              {
                targetNode: {
                  width: 80,
                  height: 50,
                  id: 'dndnode_dndnode_6',
                  position: { x: 360, y: 138.5 },
                  selectable: false,
                  data: {
                    inputs: { input1: false, input2: false },
                    outputs: { output1: false },
                    logic: 'xor',
                    connected: { after: [], before: [] },
                  },
                  type: 'custom',
                  positionAbsolute: { x: 360, y: 138.5 },
                  dragging: false,
                },
                edgeAfter: {
                  source: 'dndnode_dndnode_1',
                  sourceHandle: 'output1',
                  target: 'dndnode_dndnode_6',
                  targetHandle: 'input1',
                  id: 'reactflow__edge-dndnode_dndnode_1output1-dndnode_dndnode_6input1',
                  type: 'custom',
                },
              },
              {
                targetNode: {
                  width: 80,
                  height: 50,
                  id: 'dndnode_dndnode_9',
                  position: { x: 331, y: 264.5 },
                  selectable: false,
                  data: {
                    inputs: { input1: false, input2: false },
                    outputs: { output1: false },
                    logic: 'and',
                    connected: { after: [], before: [] },
                  },
                  type: 'custom',
                  positionAbsolute: { x: 331, y: 264.5 },
                  dragging: false,
                },
                edgeAfter: {
                  source: 'dndnode_dndnode_1',
                  sourceHandle: 'output1',
                  target: 'dndnode_dndnode_9',
                  targetHandle: 'input1',
                  id: 'reactflow__edge-dndnode_dndnode_1output1-dndnode_dndnode_9input1',
                  type: 'custom',
                },
              },
            ],
            before: [],
          },
          name: 'A',
        },
        type: 'custom',
        width: 104,
        height: 85,
        dragging: false,
        positionAbsolute: { x: 142, y: 112.5 },
      },
      {
        id: 'dndnode_dndnode_2',
        position: { x: 141, y: 223.5 },
        selectable: false,
        data: {
          inputs: { input1: false, input2: false },
          outputs: { output1: false },
          logic: 'blockInput',
          connected: {
            after: [
              {
                targetNode: {
                  width: 80,
                  height: 50,
                  id: 'dndnode_dndnode_6',
                  position: { x: 360, y: 138.5 },
                  selectable: false,
                  data: {
                    inputs: { input1: false, input2: false },
                    outputs: { output1: false },
                    logic: 'xor',
                    connected: { after: [], before: [] },
                  },
                  type: 'custom',
                  positionAbsolute: { x: 360, y: 138.5 },
                  dragging: false,
                },
                edgeAfter: {
                  source: 'dndnode_dndnode_2',
                  sourceHandle: 'output1',
                  target: 'dndnode_dndnode_6',
                  targetHandle: 'input2',
                  id: 'reactflow__edge-dndnode_dndnode_2output1-dndnode_dndnode_6input2',
                  type: 'custom',
                },
              },
              {
                targetNode: {
                  width: 80,
                  height: 50,
                  id: 'dndnode_dndnode_9',
                  position: { x: 331, y: 264.5 },
                  selectable: false,
                  data: {
                    inputs: { input1: false, input2: false },
                    outputs: { output1: false },
                    logic: 'and',
                    connected: { after: [], before: [] },
                  },
                  type: 'custom',
                  positionAbsolute: { x: 331, y: 264.5 },
                  dragging: false,
                },
                edgeAfter: {
                  source: 'dndnode_dndnode_2',
                  sourceHandle: 'output1',
                  target: 'dndnode_dndnode_9',
                  targetHandle: 'input2',
                  id: 'reactflow__edge-dndnode_dndnode_2output1-dndnode_dndnode_9input2',
                  type: 'custom',
                },
              },
            ],
            before: [],
          },
          name: 'B',
        },
        type: 'custom',
        width: 104,
        height: 85,
        positionAbsolute: { x: 141, y: 223.5 },
        dragging: false,
      },
      {
        id: 'dndnode_dndnode_3',
        position: { x: 143, y: 348.5 },
        selectable: false,
        data: {
          inputs: { input1: false, input2: false },
          outputs: { output1: false },
          logic: 'blockInput',
          connected: {
            after: [
              {
                targetNode: {
                  width: 80,
                  height: 50,
                  id: 'dndnode_dndnode_7',
                  position: { x: 600, y: 196.5 },
                  selectable: false,
                  data: {
                    inputs: { input1: false, input2: false },
                    outputs: { output1: false },
                    logic: 'xor',
                    connected: { after: [], before: [] },
                  },
                  type: 'custom',
                  positionAbsolute: { x: 600, y: 196.5 },
                  dragging: false,
                },
                edgeAfter: {
                  source: 'dndnode_dndnode_3',
                  sourceHandle: 'output1',
                  target: 'dndnode_dndnode_7',
                  targetHandle: 'input2',
                  id: 'reactflow__edge-dndnode_dndnode_3output1-dndnode_dndnode_7input2',
                  type: 'custom',
                },
              },
              {
                targetNode: {
                  width: 80,
                  height: 50,
                  id: 'dndnode_dndnode_8',
                  position: { x: 480, y: 313.5 },
                  selectable: false,
                  data: {
                    inputs: { input1: false, input2: false },
                    outputs: { output1: false },
                    logic: 'and',
                    connected: { after: [], before: [] },
                  },
                  type: 'custom',
                  positionAbsolute: { x: 480, y: 313.5 },
                  dragging: false,
                },
                edgeAfter: {
                  source: 'dndnode_dndnode_3',
                  sourceHandle: 'output1',
                  target: 'dndnode_dndnode_8',
                  targetHandle: 'input2',
                  id: 'reactflow__edge-dndnode_dndnode_3output1-dndnode_dndnode_8input2',
                  type: 'custom',
                },
              },
            ],
            before: [],
          },
          name: 'Carry in',
        },
        type: 'custom',
        width: 104,
        height: 85,
        positionAbsolute: { x: 143, y: 348.5 },
        dragging: false,
      },
      {
        id: 'dndnode_dndnode_4',
        position: { x: 729, y: 160.5 },
        selectable: false,
        data: {
          inputs: { input1: false, input2: false },
          outputs: { output1: false },
          logic: 'blockOutput',
          connected: {
            after: [],
            before: [
              {
                sourceNode: {
                  width: 80,
                  height: 50,
                  id: 'dndnode_dndnode_7',
                  position: { x: 600, y: 196.5 },
                  selectable: false,
                  data: {
                    inputs: { input1: false, input2: false },
                    outputs: { output1: false },
                    logic: 'xor',
                    connected: { after: [], before: [] },
                  },
                  type: 'custom',
                  positionAbsolute: { x: 600, y: 196.5 },
                  dragging: false,
                },
                edgeBefore: {
                  source: 'dndnode_dndnode_7',
                  sourceHandle: 'output1',
                  target: 'dndnode_dndnode_4',
                  targetHandle: 'input1',
                  id: 'reactflow__edge-dndnode_dndnode_7output1-dndnode_dndnode_4input1',
                  type: 'custom',
                },
              },
            ],
          },
          name: 'Sum',
        },
        type: 'custom',
        width: 104,
        height: 85,
        positionAbsolute: { x: 729, y: 160.5 },
        dragging: false,
      },
      {
        id: 'dndnode_dndnode_5',
        position: { x: 730, y: 279.5 },
        selectable: false,
        data: {
          inputs: { input1: false, input2: false },
          outputs: { output1: false },
          logic: 'blockOutput',
          connected: {
            after: [],
            before: [
              {
                sourceNode: {
                  width: 80,
                  height: 50,
                  id: 'dndnode_dndnode_10',
                  position: { x: 598, y: 287.5 },
                  selectable: false,
                  data: {
                    inputs: { input1: false, input2: false },
                    outputs: { output1: false },
                    logic: 'or',
                    connected: { after: [], before: [] },
                  },
                  type: 'custom',
                  positionAbsolute: { x: 598, y: 287.5 },
                  dragging: false,
                },
                edgeBefore: {
                  source: 'dndnode_dndnode_10',
                  sourceHandle: 'output1',
                  target: 'dndnode_dndnode_5',
                  targetHandle: 'input1',
                  id: 'reactflow__edge-dndnode_dndnode_10output1-dndnode_dndnode_5input1',
                  type: 'custom',
                },
              },
            ],
          },
          name: 'Carry out',
        },
        type: 'custom',
        width: 104,
        height: 85,
        positionAbsolute: { x: 730, y: 279.5 },
        dragging: false,
      },
      {
        id: 'dndnode_dndnode_6',
        position: { x: 360, y: 138.5 },
        selectable: false,
        data: {
          inputs: { input1: false, input2: false },
          outputs: { output1: false },
          logic: 'xor',
          connected: {
            after: [
              {
                targetNode: {
                  width: 80,
                  height: 50,
                  id: 'dndnode_dndnode_7',
                  position: { x: 600, y: 196.5 },
                  selectable: false,
                  data: {
                    inputs: { input1: false, input2: false },
                    outputs: { output1: false },
                    logic: 'xor',
                    connected: { after: [], before: [] },
                  },
                  type: 'custom',
                  positionAbsolute: { x: 600, y: 196.5 },
                  dragging: false,
                },
                edgeAfter: {
                  source: 'dndnode_dndnode_6',
                  sourceHandle: 'output1',
                  target: 'dndnode_dndnode_7',
                  targetHandle: 'input1',
                  id: 'reactflow__edge-dndnode_dndnode_6output1-dndnode_dndnode_7input1',
                  type: 'custom',
                },
              },
              {
                targetNode: {
                  width: 80,
                  height: 50,
                  id: 'dndnode_dndnode_8',
                  position: { x: 480, y: 313.5 },
                  selectable: false,
                  data: {
                    inputs: { input1: false, input2: false },
                    outputs: { output1: false },
                    logic: 'and',
                    connected: { after: [], before: [] },
                  },
                  type: 'custom',
                  positionAbsolute: { x: 480, y: 313.5 },
                  dragging: false,
                },
                edgeAfter: {
                  source: 'dndnode_dndnode_6',
                  sourceHandle: 'output1',
                  target: 'dndnode_dndnode_8',
                  targetHandle: 'input1',
                  id: 'reactflow__edge-dndnode_dndnode_6output1-dndnode_dndnode_8input1',
                  type: 'custom',
                },
              },
            ],
            before: [
              {
                sourceNode: {
                  width: 104,
                  height: 85,
                  id: 'dndnode_dndnode_1',
                  position: { x: 142, y: 112.5 },
                  selectable: false,
                  data: {
                    inputs: { input1: false, input2: false },
                    outputs: { output1: false },
                    logic: 'blockInput',
                    connected: { after: [], before: [] },
                    name: 'A',
                  },
                  type: 'custom',
                  dragging: false,
                  positionAbsolute: { x: 142, y: 112.5 },
                },
                edgeBefore: {
                  source: 'dndnode_dndnode_1',
                  sourceHandle: 'output1',
                  target: 'dndnode_dndnode_6',
                  targetHandle: 'input1',
                  id: 'reactflow__edge-dndnode_dndnode_1output1-dndnode_dndnode_6input1',
                  type: 'custom',
                },
              },
              {
                sourceNode: {
                  width: 104,
                  height: 85,
                  id: 'dndnode_dndnode_2',
                  position: { x: 144, y: 229.5 },
                  selectable: false,
                  data: {
                    inputs: { input1: false, input2: false },
                    outputs: { output1: false },
                    logic: 'blockInput',
                    connected: { after: [], before: [] },
                    name: 'B',
                  },
                  type: 'custom',
                  positionAbsolute: { x: 144, y: 229.5 },
                  dragging: false,
                },
                edgeBefore: {
                  source: 'dndnode_dndnode_2',
                  sourceHandle: 'output1',
                  target: 'dndnode_dndnode_6',
                  targetHandle: 'input2',
                  id: 'reactflow__edge-dndnode_dndnode_2output1-dndnode_dndnode_6input2',
                  type: 'custom',
                },
              },
            ],
          },
        },
        type: 'custom',
        width: 80,
        height: 50,
        positionAbsolute: { x: 360, y: 138.5 },
        dragging: false,
      },
      {
        id: 'dndnode_dndnode_7',
        position: { x: 600, y: 196.5 },
        selectable: false,
        data: {
          inputs: { input1: false, input2: false },
          outputs: { output1: false },
          logic: 'xor',
          connected: {
            after: [
              {
                targetNode: {
                  width: 104,
                  height: 85,
                  id: 'dndnode_dndnode_4',
                  position: { x: 729, y: 160.5 },
                  selectable: false,
                  data: {
                    inputs: { input1: false, input2: false },
                    outputs: { output1: false },
                    logic: 'blockOutput',
                    connected: { after: [], before: [] },
                    name: 'Sum',
                  },
                  type: 'custom',
                  positionAbsolute: { x: 729, y: 160.5 },
                  dragging: false,
                },
                edgeAfter: {
                  source: 'dndnode_dndnode_7',
                  sourceHandle: 'output1',
                  target: 'dndnode_dndnode_4',
                  targetHandle: 'input1',
                  id: 'reactflow__edge-dndnode_dndnode_7output1-dndnode_dndnode_4input1',
                  type: 'custom',
                },
              },
            ],
            before: [
              {
                sourceNode: {
                  width: 80,
                  height: 50,
                  id: 'dndnode_dndnode_6',
                  position: { x: 360, y: 138.5 },
                  selectable: false,
                  data: {
                    inputs: { input1: false, input2: false },
                    outputs: { output1: false },
                    logic: 'xor',
                    connected: { after: [], before: [] },
                  },
                  type: 'custom',
                  positionAbsolute: { x: 360, y: 138.5 },
                  dragging: false,
                },
                edgeBefore: {
                  source: 'dndnode_dndnode_6',
                  sourceHandle: 'output1',
                  target: 'dndnode_dndnode_7',
                  targetHandle: 'input1',
                  id: 'reactflow__edge-dndnode_dndnode_6output1-dndnode_dndnode_7input1',
                  type: 'custom',
                },
              },
              {
                sourceNode: {
                  width: 104,
                  height: 85,
                  id: 'dndnode_dndnode_3',
                  position: { x: 143, y: 348.5 },
                  selectable: false,
                  data: {
                    inputs: { input1: false, input2: false },
                    outputs: { output1: false },
                    logic: 'blockInput',
                    connected: { after: [], before: [] },
                    name: 'Carry in',
                  },
                  type: 'custom',
                  positionAbsolute: { x: 143, y: 348.5 },
                  dragging: false,
                },
                edgeBefore: {
                  source: 'dndnode_dndnode_3',
                  sourceHandle: 'output1',
                  target: 'dndnode_dndnode_7',
                  targetHandle: 'input2',
                  id: 'reactflow__edge-dndnode_dndnode_3output1-dndnode_dndnode_7input2',
                  type: 'custom',
                },
              },
            ],
          },
        },
        type: 'custom',
        width: 80,
        height: 50,
        positionAbsolute: { x: 600, y: 196.5 },
        dragging: false,
      },
      {
        id: 'dndnode_dndnode_8',
        position: { x: 480, y: 313.5 },
        selectable: false,
        data: {
          inputs: { input1: false, input2: false },
          outputs: { output1: false },
          logic: 'and',
          connected: {
            after: [
              {
                targetNode: {
                  width: 80,
                  height: 50,
                  id: 'dndnode_dndnode_10',
                  position: { x: 598, y: 287.5 },
                  selectable: false,
                  data: {
                    inputs: { input1: false, input2: false },
                    outputs: { output1: false },
                    logic: 'or',
                    connected: { after: [], before: [] },
                  },
                  type: 'custom',
                  positionAbsolute: { x: 598, y: 287.5 },
                  dragging: false,
                },
                edgeAfter: {
                  source: 'dndnode_dndnode_8',
                  sourceHandle: 'output1',
                  target: 'dndnode_dndnode_10',
                  targetHandle: 'input2',
                  id: 'reactflow__edge-dndnode_dndnode_8output1-dndnode_dndnode_10input2',
                  type: 'custom',
                },
              },
            ],
            before: [
              {
                sourceNode: {
                  width: 80,
                  height: 50,
                  id: 'dndnode_dndnode_6',
                  position: { x: 360, y: 138.5 },
                  selectable: false,
                  data: {
                    inputs: { input1: false, input2: false },
                    outputs: { output1: false },
                    logic: 'xor',
                    connected: { after: [], before: [] },
                  },
                  type: 'custom',
                  positionAbsolute: { x: 360, y: 138.5 },
                  dragging: false,
                },
                edgeBefore: {
                  source: 'dndnode_dndnode_6',
                  sourceHandle: 'output1',
                  target: 'dndnode_dndnode_8',
                  targetHandle: 'input1',
                  id: 'reactflow__edge-dndnode_dndnode_6output1-dndnode_dndnode_8input1',
                  type: 'custom',
                },
              },
              {
                sourceNode: {
                  width: 104,
                  height: 85,
                  id: 'dndnode_dndnode_3',
                  position: { x: 143, y: 348.5 },
                  selectable: false,
                  data: {
                    inputs: { input1: false, input2: false },
                    outputs: { output1: false },
                    logic: 'blockInput',
                    connected: { after: [], before: [] },
                    name: 'Carry in',
                  },
                  type: 'custom',
                  positionAbsolute: { x: 143, y: 348.5 },
                  dragging: false,
                },
                edgeBefore: {
                  source: 'dndnode_dndnode_3',
                  sourceHandle: 'output1',
                  target: 'dndnode_dndnode_8',
                  targetHandle: 'input2',
                  id: 'reactflow__edge-dndnode_dndnode_3output1-dndnode_dndnode_8input2',
                  type: 'custom',
                },
              },
            ],
          },
        },
        type: 'custom',
        width: 80,
        height: 50,
        positionAbsolute: { x: 480, y: 313.5 },
        dragging: false,
      },
      {
        id: 'dndnode_dndnode_9',
        position: { x: 331, y: 264.5 },
        selectable: false,
        data: {
          inputs: { input1: false, input2: false },
          outputs: { output1: false },
          logic: 'and',
          connected: {
            after: [
              {
                targetNode: {
                  width: 80,
                  height: 50,
                  id: 'dndnode_dndnode_10',
                  position: { x: 598, y: 287.5 },
                  selectable: false,
                  data: {
                    inputs: { input1: false, input2: false },
                    outputs: { output1: false },
                    logic: 'or',
                    connected: { after: [], before: [] },
                  },
                  type: 'custom',
                  positionAbsolute: { x: 598, y: 287.5 },
                  dragging: false,
                },
                edgeAfter: {
                  source: 'dndnode_dndnode_9',
                  sourceHandle: 'output1',
                  target: 'dndnode_dndnode_10',
                  targetHandle: 'input1',
                  id: 'reactflow__edge-dndnode_dndnode_9output1-dndnode_dndnode_10input1',
                  type: 'custom',
                },
              },
            ],
            before: [
              {
                sourceNode: {
                  width: 104,
                  height: 85,
                  id: 'dndnode_dndnode_1',
                  position: { x: 142, y: 112.5 },
                  selectable: false,
                  data: {
                    inputs: { input1: false, input2: false },
                    outputs: { output1: false },
                    logic: 'blockInput',
                    connected: { after: [], before: [] },
                    name: 'A',
                  },
                  type: 'custom',
                  dragging: false,
                  positionAbsolute: { x: 142, y: 112.5 },
                },
                edgeBefore: {
                  source: 'dndnode_dndnode_1',
                  sourceHandle: 'output1',
                  target: 'dndnode_dndnode_9',
                  targetHandle: 'input1',
                  id: 'reactflow__edge-dndnode_dndnode_1output1-dndnode_dndnode_9input1',
                  type: 'custom',
                },
              },
              {
                sourceNode: {
                  width: 104,
                  height: 85,
                  id: 'dndnode_dndnode_2',
                  position: { x: 144, y: 229.5 },
                  selectable: false,
                  data: {
                    inputs: { input1: false, input2: false },
                    outputs: { output1: false },
                    logic: 'blockInput',
                    connected: { after: [], before: [] },
                    name: 'B',
                  },
                  type: 'custom',
                  positionAbsolute: { x: 144, y: 229.5 },
                  dragging: false,
                },
                edgeBefore: {
                  source: 'dndnode_dndnode_2',
                  sourceHandle: 'output1',
                  target: 'dndnode_dndnode_9',
                  targetHandle: 'input2',
                  id: 'reactflow__edge-dndnode_dndnode_2output1-dndnode_dndnode_9input2',
                  type: 'custom',
                },
              },
            ],
          },
        },
        type: 'custom',
        width: 80,
        height: 50,
        positionAbsolute: { x: 331, y: 264.5 },
        dragging: false,
      },
      {
        id: 'dndnode_dndnode_10',
        position: { x: 598, y: 287.5 },
        selectable: false,
        data: {
          inputs: { input1: false, input2: false },
          outputs: { output1: false },
          logic: 'or',
          connected: {
            after: [
              {
                targetNode: {
                  width: 104,
                  height: 85,
                  id: 'dndnode_dndnode_5',
                  position: { x: 730, y: 279.5 },
                  selectable: false,
                  data: {
                    inputs: { input1: false, input2: false },
                    outputs: { output1: false },
                    logic: 'blockOutput',
                    connected: { after: [], before: [] },
                    name: 'Carry out',
                  },
                  type: 'custom',
                  positionAbsolute: { x: 730, y: 279.5 },
                  dragging: false,
                },
                edgeAfter: {
                  source: 'dndnode_dndnode_10',
                  sourceHandle: 'output1',
                  target: 'dndnode_dndnode_5',
                  targetHandle: 'input1',
                  id: 'reactflow__edge-dndnode_dndnode_10output1-dndnode_dndnode_5input1',
                  type: 'custom',
                },
              },
            ],
            before: [
              {
                sourceNode: {
                  width: 80,
                  height: 50,
                  id: 'dndnode_dndnode_9',
                  position: { x: 331, y: 264.5 },
                  selectable: false,
                  data: {
                    inputs: { input1: false, input2: false },
                    outputs: { output1: false },
                    logic: 'and',
                    connected: { after: [], before: [] },
                  },
                  type: 'custom',
                  positionAbsolute: { x: 331, y: 264.5 },
                  dragging: false,
                },
                edgeBefore: {
                  source: 'dndnode_dndnode_9',
                  sourceHandle: 'output1',
                  target: 'dndnode_dndnode_10',
                  targetHandle: 'input1',
                  id: 'reactflow__edge-dndnode_dndnode_9output1-dndnode_dndnode_10input1',
                  type: 'custom',
                },
              },
              {
                sourceNode: {
                  width: 80,
                  height: 50,
                  id: 'dndnode_dndnode_8',
                  position: { x: 480, y: 313.5 },
                  selectable: false,
                  data: {
                    inputs: { input1: false, input2: false },
                    outputs: { output1: false },
                    logic: 'and',
                    connected: { after: [], before: [] },
                  },
                  type: 'custom',
                  positionAbsolute: { x: 480, y: 313.5 },
                  dragging: false,
                },
                edgeBefore: {
                  source: 'dndnode_dndnode_8',
                  sourceHandle: 'output1',
                  target: 'dndnode_dndnode_10',
                  targetHandle: 'input2',
                  id: 'reactflow__edge-dndnode_dndnode_8output1-dndnode_dndnode_10input2',
                  type: 'custom',
                },
              },
            ],
          },
        },
        type: 'custom',
        width: 80,
        height: 50,
        positionAbsolute: { x: 598, y: 287.5 },
        dragging: false,
      },
    ],
    edges: [
      {
        source: 'dndnode_dndnode_1',
        sourceHandle: 'output1',
        target: 'dndnode_dndnode_6',
        targetHandle: 'input1',
        id: 'reactflow__edge-dndnode_dndnode_1output1-dndnode_dndnode_6input1',
        type: 'custom',
      },
      {
        source: 'dndnode_dndnode_1',
        sourceHandle: 'output1',
        target: 'dndnode_dndnode_9',
        targetHandle: 'input1',
        id: 'reactflow__edge-dndnode_dndnode_1output1-dndnode_dndnode_9input1',
        type: 'custom',
      },
      {
        source: 'dndnode_dndnode_2',
        sourceHandle: 'output1',
        target: 'dndnode_dndnode_6',
        targetHandle: 'input2',
        id: 'reactflow__edge-dndnode_dndnode_2output1-dndnode_dndnode_6input2',
        type: 'custom',
      },
      {
        source: 'dndnode_dndnode_2',
        sourceHandle: 'output1',
        target: 'dndnode_dndnode_9',
        targetHandle: 'input2',
        id: 'reactflow__edge-dndnode_dndnode_2output1-dndnode_dndnode_9input2',
        type: 'custom',
      },
      {
        source: 'dndnode_dndnode_6',
        sourceHandle: 'output1',
        target: 'dndnode_dndnode_7',
        targetHandle: 'input1',
        id: 'reactflow__edge-dndnode_dndnode_6output1-dndnode_dndnode_7input1',
        type: 'custom',
      },
      {
        source: 'dndnode_dndnode_6',
        sourceHandle: 'output1',
        target: 'dndnode_dndnode_8',
        targetHandle: 'input1',
        id: 'reactflow__edge-dndnode_dndnode_6output1-dndnode_dndnode_8input1',
        type: 'custom',
      },
      {
        source: 'dndnode_dndnode_3',
        sourceHandle: 'output1',
        target: 'dndnode_dndnode_7',
        targetHandle: 'input2',
        id: 'reactflow__edge-dndnode_dndnode_3output1-dndnode_dndnode_7input2',
        type: 'custom',
      },
      {
        source: 'dndnode_dndnode_3',
        sourceHandle: 'output1',
        target: 'dndnode_dndnode_8',
        targetHandle: 'input2',
        id: 'reactflow__edge-dndnode_dndnode_3output1-dndnode_dndnode_8input2',
        type: 'custom',
      },
      {
        source: 'dndnode_dndnode_9',
        sourceHandle: 'output1',
        target: 'dndnode_dndnode_10',
        targetHandle: 'input1',
        id: 'reactflow__edge-dndnode_dndnode_9output1-dndnode_dndnode_10input1',
        type: 'custom',
      },
      {
        source: 'dndnode_dndnode_8',
        sourceHandle: 'output1',
        target: 'dndnode_dndnode_10',
        targetHandle: 'input2',
        id: 'reactflow__edge-dndnode_dndnode_8output1-dndnode_dndnode_10input2',
        type: 'custom',
      },
      {
        source: 'dndnode_dndnode_7',
        sourceHandle: 'output1',
        target: 'dndnode_dndnode_4',
        targetHandle: 'input1',
        id: 'reactflow__edge-dndnode_dndnode_7output1-dndnode_dndnode_4input1',
        type: 'custom',
      },
      {
        source: 'dndnode_dndnode_10',
        sourceHandle: 'output1',
        target: 'dndnode_dndnode_5',
        targetHandle: 'input1',
        id: 'reactflow__edge-dndnode_dndnode_10output1-dndnode_dndnode_5input1',
        type: 'custom',
      },
    ],
    autosave: false,
    upToDate: true,
  },
]
